---
- name: Restart mariadb
  ansible.builtin.service:
    name: mariadb
    state: restarted
  when:
    - mariadb_can_restart
    - not ansible_check_mode

- name: Setup MariaDB
  ansible.builtin.command: /etc/init.d/mariadb setup
  changed_when: false
