---
dependencies: []

galaxy_info:
  author: fauust
  role_name: mariadb
  description: MariaDB server for Linux.
  license: license GPL-3.0-only
  min_ansible_version: "2.8"
  github_branch: main
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Alpine
      versions:
        - all
  galaxy_tags:
    - mariadb
    - mysql
